### PR TITLE
Enable Bootstrap SASS. UI changes to make main container more responsive

### PR DESCRIPTION
**Pull request by sweigardc**
Keeping it simple for the first commit

### CODE REVIEW

**Comment by patrickomatic** [comment]
Looks great thank you so much!  Simple is great for now.  One question - looks like it kinda broke the styling of the "reputation" box on the user page?  I'll take a look at it real quick, probably isn't a big deal

**Comment by sweigardc** [comment]
Oops, sorry about that. I still need setup test data and the .env file to thoroughly test it out. Will work on getting that setup this week, any help appreciated.

**Comment by patrickomatic** [comment]
Cool sorry I spaced on your reddit PMs about the credentials (crazy busy weekend) - I'll get you added to those so you can do local dev

**Comment by patrickomatic** [comment]
I messed with this some last night and fixed it up and deployed it.  Just FYI part of what I had to do was change application.sass to application.scss.  Let's try to stick with SCSS rather than SASS if possible.  Happy to help refactor any SASS to SCSS that you may have already written

**Comment by sweigardc** [comment]
Cool, happy to stick with SCSS. Saw I wasn't importing those other files, thanks for fixing. Question about functionality, if you complete a trade by selecting Positive checkbox but don't leave feedback, it stays in-complete. Did you want to require a comment or should trades close out as soon as both parties hit submit with one of the checkboxes selected?

**Comment by patrickomatic** [comment]
Hmmm it should give you a validation error if you don't fill out the feedback and just check the checkbox... I'll take a look at that tonight and make sure it's doing validation properly

**Pull request merged**
